# Generated by Django 5.0.6 on 2024-07-29 14:22

import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='storage_path',
            field=models.FileField(upload_to=storage.models.user_directory_path),
        ),
    ]
