# Generated by Django 5.0.7 on 2024-08-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_file_storage_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='share_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
